apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: microservices-secure-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: 632127306880.dkr.ecr.ap-south-1.amazonaws.com/product-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        env:
        - name: APP_ENV
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: APP_ENV
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: microservices-secure-ns
spec:
  selector:
    app: product-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
  type: ClusterIP
